symfony/src/Entity/OrderItem.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrderItemRepository")
 */
class OrderItem
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="decimal", precision=8, scale=2)
     */
    private $quantity;

    /**
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Product")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Order", inversedBy="orderItems")
     * @ORM\JoinColumn(name="_order", nullable=false)
     */
    private $order;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity()
    {
        return $this->quantity;
    }

    public function setQuantity($quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getProduct(): ?Product
    {
        return $this->product;
    }

    public function setProduct(?Product $product): self
    {
        $this->product = $product;

        return $this;
    }

    public function getOrder(): ?Order
    {
        return $this->order;
    }

    public function setOrder(?Order $order): self
    {
        $this->order = $order;

        return $this;
    }

    public function getSum(): string
    {
        return (string) $this->product->getPrice() * $this->quantity;
    }
}

symfony/src/Form/AutocompleteType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Routing\RouterInterface;

class AutocompleteType extends AbstractType
{
    /**
     * @var RouterInterface
     */
    private $router;

    /**
     * @param RouterInterface $router
     */
    public function __construct(RouterInterface $router)
    {
        $this->router = $router;
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['handler'] = $options['handler'];
    }

    public function getBlockPrefix()
    {
        return 'app_autocomplete';
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired(['handler']);
        $resolver->setAllowedTypes('handler', ['string']);
    }

    public function getParent()
    {
        return EntityType::class;
    }
}

symfony/src/Form/OrderItemType.php
<?php

namespace App\Form;

use App\Entity\OrderItem;
use App\Entity\Product;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrderItemType extends AbstractType
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('product', AutocompleteType::class, ['handler' => 'productRepository.getAutocompleteOptions', 'class' => Product::class])
            ->add('quantity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => OrderItem::class,
        ]);
    }
}

symfony/templates/orderItems/form.html.twig
{% form_theme _self as _form_theme %}

{% block _order_orderItems_widget %}
    {% spaceless %}

        {% import _self as helper %}

        <table
                class="table list"
                data-item-counter="{{ value.count }}"
                data-item-template="_order_orderItems_orderItem_template"
                id="{{ id }}"
        >
            <thead>
                <tr>
                    <th>Nr</th>
                    <th style="width: 15em">Product</th>
                    <th>Amount</th>
                    <th>Price</th>
                    <th>Quantity</th>
                    <th>Sum</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

            {{ block('_order_orderItems_orderItem_template') }}

            {% for item in form %}
                {{ helper.form_collection_entry(item) }}
            {% endfor %}
            </tbody>
        </table>

        {% if form.parent.vars.value.status == 'pending' or form.parent.vars.value.id is null %}
        <button
                class="btn info form-collection-add-new-entry"
                data-collection-holder="{{ id }}"
                id="_order_orderItems_orderItem_add_new"
                type="button"
        >
            Add
        </button>
        {% endif %}

    {% endspaceless %}
{% endblock %}

{% macro form_collection_entry(entry) %}

    {% import _self as helper %}

    {% set orderItem = entry.vars.data | default(null) %}
    {% set product = entry.product.vars.data | default(null) %}
    {% set autocompleteOff = {'attr': {'autocomplete': 'off'}} %}

    <tr>
        <td class="_order_orderItems_orderItem_index"></td>
        <td class="{{ helper.has_errors(entry.product, 'error') }}">{{ form_widget(entry.product) }}</td>
        <td class="_order_orderItems_orderItem_product_amount">{{ product.amount | default(0) | number_format(2, '.', ' ') }} {{ product.unit | default | default('') }}</td>
        <td class="_order_orderItems_orderItem_product_price">{{ product.price | default(0) | number_format(2, '.', ' ') }}</td>
        <td class="{{ helper.has_errors(entry.quantity, 'error') }}">{{ form_widget(entry.quantity, autocompleteOff) }}</td>
        <td class="_order_orderItems_orderItem_sum">{{ orderItem.sum | default(0) | number_format(2, '.', ' ') }}</td>
        <td class="action">
            <div>
                <a class="list-action-btn _order_orderItems_orderItem_delete_item">
                    <span><i class="fa fa-trash-o"></i></span>
                </a>
            </div>
        </td>
    </tr>
{% endmacro %}

{% macro has_errors(form_view, error_class) %}
    {{ form_view.vars.errors.count > 0 ? error_class : '' }}
{% endmacro %}

{% block _order_orderItems_orderItem_template %}

    {% import _self as helper%}

    <template id="_order_orderItems_orderItem_template">
        {{ helper.form_collection_entry(prototype.children) }}
    </template>

{% endblock %}

symfony/templates/orderItems/show.html.twig
{% import _self as _form %}

<table class="table list">
    <thead>
        <tr>
            <th>Nr</th>
            <th>Product</th>
            <th>Amount</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Sum</th>
        </tr>
    </thead>
    <tbody>
    {% for item in items %}
        {{ _form.row(item, loop.index) }}
    {% endfor %}
    </tbody>
</table>

{% macro row(item, index) %}
    <tr {{ item.product.deleted ? 'class="deleted-product-warning"' : '' }}>
        <td>{{ index }}</td>
        <td>{{ item.product.name }}</td>
        <td>{{ item.product.amount | number_format(2, '.', ' ') }} {{ item.product.unit }}</td>
        <td>{{ item.product.price | number_format(2, '.', ' ') }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ (item.quantity * item.product.price) | number_format(2, '.', ' ') }}</td>
    </tr>
{% endmacro %}